function import_ChemSim(force)
% import_ChemSim
% import the cehnical similarity from the data file (generated by Jeremy)
%   [optional] metric: either morgan [default] or AtomPair
%
%       NOTE: not using metric will not reinitialize the variable if already
%               imported
%
% global variable:    ChemSim:
%   ChemSim.HMSLids: HSMLids corresponding to the matrix
%   ChemSim.Morgan : Morgan distance 
%   Chem.AtomPair  : Atom Pair distance


global ChemSimReference
if isempty(ChemSimReference) || (exist('force','var') && force)
    
    ChemSimReference.HMSLids = importdata('../data/hmsl_small_molecule_similarity_ids.txt');
    for i=1:length(ChemSimReference.HMSLids)
        ChemSimReference.HMSLids{i} = ['HMSL' ChemSimReference.HMSLids{i}(1:(find(ChemSimReference.HMSLids{i}=='-',1,'first')-1))];
    end
    %%
    ChemSimReference.Morgan = importdata('../data/hmsl_small_molecule_similarity_morgan.tsv');
    ChemSimReference.AtomPair = importdata('../data/hmsl_small_molecule_similarity_atom_pairs.tsv');    
    
end